apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-dz02-helm.fullname" . }}-configmap
data:
  username: {{ .Values.postgresql.postgresqlUsername | quote  }}
  POSTGRES_DB:  {{ .Values.postgresql.postgresqlDatabase  | quote }}